services:
  - type: web
    name: mi-app-de-tareas
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn organizador.wsgi"
    staticPublishPath: staticfiles
