# Generated by Django 5.2 on 2025-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarea",
            options={"ordering": ["fecha_limite"]},
        ),
        migrations.AddField(
            model_name="tarea",
            name="completada",
            field=models.BooleanField(default=False),
        ),
    ]
