# Generated by Django 5.2 on 2025-04-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0002_alter_tarea_options_tarea_completada"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="tipo",
            field=models.CharField(
                choices=[("T", "Tarea"), ("P", "Parcial"), ("Q", "Quiz")],
                default="T",
                max_length=1,
            ),
        ),
    ]
